<div class="grid-x grid-padding-x" style="text-align: left">
    <div class="large-6 cell">
<img src="<?=App::config('url')?>public/img/loora-11.webp " alt="Loora dvoriste">
</div>
    <div class="large-6 cell">
    </div>
</div>

<div class="grid-x grid-padding-x" style="text-align: right">
    <div class="large-6 cell">
<img src="<?=App::config('url')?>public/img/loora-001.webp " alt="Loora dvoriste 2">
</div>
    <div class="large-6 cell">
    </div>
</div>