<div class="grid-x grid-padding-x" style="text-align: left">
    <div class="large-6 cell">
<img src="<?=App::config('url')?>public/img/loora-11.webp " alt="Loora dvoriste">
<h1 style="font-family:Brush Script MT, Brush Script Std, cursive;
font-size:100px;">
    Loora Mjesto gdje gost postaje prijatelj
</h1>
</div>
    <div class="large-6 cell">
    <img src="<?=App::config('url')?>public/img/loora-001.webp " alt="Loora dvoriste 2">
    </div>
</div>

