<div class="title-bar" data-responsive-toggle="example-menu" data-hide-for="medium">
  <button class="menu-icon" type="button" data-toggle></button>
  <div class="title-bar-title"><?=App::config('naslovApp')?></div>
</div>

<div style=background-color:black;" class="top-bar" id="example-menu">
  <div style= background-color:black;" class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <li class="menu-text"><?=App::config('naslovApp')?></li>
      <li><a href="<?=App::config('url')?>">Početna</a></li>
      <?php if(App::autoriziran()):?>
        <li><a href="<?=App::config('url')?>nadzornaploca/index">Nadzorna ploča</a></li>
  

      <?php endif;?>
        
    
      </li>
      <li><a href="<?=App::config('url')?>pice/index">Piće</a></li>
      <li><a href="<?=App::config('url')?>jelo/index">Jelo</a></li>
      <li><a href="<?=App::config('url')?>mjesto/index">mjesto</a></li>
      <li><a href="<?=App::config('url')?>rezervacija/index">Rezervacija</a></li>
   
    </ul>
  </div>
  <div class="top-bar-right">
    <ul class="menu">
      
      
    <li>
        <?php if(App::autoriziran()):?>
          <a href="<?=App::config('url')?>login/odjava">Odjavi <?php echo $_SESSION['autoriziran']->ime ?></a>
        <?php else:?>
          <a href="<?=App::config('url')?>login/index">Login</a>
        <?php endif;?>
      </li>
    </ul>
  </div>
</div>