<div class="title-bar" data-responsive-toggle="example-menu" data-hide-for="medium">
  <button class="menu-icon" type="button" data-toggle></button>
  <div class="title-bar-title"><?=App::config('naslovApp')?></div>
</div>

<div class="top-bar" id="example-menu">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <li class="menu-text"><?=App::config('naslovApp')?></li>
      <li class="has-submenu">
        <a href="#0">One</a>
        <ul class="submenu menu vertical" data-submenu>
          <li><a href="#0">O nama</a></li>
        
        </ul>
      </li>
      <li><a href="#0">Jelovnik</a></li>
      <li><a href="#0">Rezervacija</a></li>
    </ul>
  </div>
  <div class="top-bar-right">
    <ul class="menu">
      
      <li><button type="button" class="button">Prijava</button></li>
    </ul>
  </div>
</div>