
    
<div class="grid-x">
    <div class ="cell-large-6" style="display:flex; align-items:center">
    <p class="h1">Pića</p>
    <i 
        style="color:#007bff; margin-left:10px" 
        class="fas fa-2x fa-beer">
    </i> </p>
    <a href="<?=App::config('url') ?>pice/novi"><i 
 style="color:#007bff; margin-left:10px"
 title="Dodaj novi" 
 class="fas fa-2x fa-plus"></i></a>
    </div>
</div class ="cell-large-6" style="tet-align:right;">


<table class="table">
    <thead class="thead-dark"> 
        <tr>
            <th>Naziv</th>
            <th>Cijena</th>
            <th>Vrsta</th>
            <th>Akcija</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($pice as $pica): ?>
            <tr>
                <td><?=$pica->naziv?></td>
                <td><?=$pica->cijena?> </td>
                <td><?=$pica->vrsta?></td>
                <td>
                    <a href="<?=App::config('url') ?>pice/promjena/<?=$pica->sifra?>">
                    <i style="color: black;"
                    title="promjeni" 
                    class="fas fa-2x fa-pen"></i>
                    </a>

                    <a href="<?=App::config('url') ?>pice/brisanje/<?=$pica->sifra?>">
                    <i style="margin-left:20px;"
                    title="izbrisi" 
                    class="fas fa-2x fa-trash"></i>
                    </a>
                </td>

            </tr>
        <?php endforeach; ?>
    </tbody>
</table>

    



