<form action="<?=App::config('url') ?>pice/promjeni" method="post">
<fieldset>
 <legend>
     Promjena Pića
 </legend>
</fieldset>
<label>
    <h3>Naziv</h3>
<label for="naziv"></label>
<input type="text" name="naziv" id="sifra">
</label>
<h3>Cijena</h3>
<label for="Cijena"></label>
<input type="number" name="cijena" id="sifra">
<h3>Vrsta</h3>
<label for="vrsta"></label>
<input type="text" name="vrsta" id="sifra">

<input type="hidden" name="sifra" value="<?=$pice->sifra?>">

<div class="grid-x grid-padding-x">
    <div class="large-4 cell">
    <a class="alert button expanded"
    href="<?=App::config('url')?>pice/index">Odustani </a>   
    </div>
    <div class="large-8cell"></div>
    <input type="submit" class="success button expanded" value="Promjeni ">
</div>


</form>
