<form action="<?=App::config('url') ?>pice/promjeni" method="post">
<fieldset>
<div style="display:flex; justify-content:center ">
    <div style="width:600px; ">

<p class="h1">Uredi piće</p>

<label>
    <h3>Naziv</h3>
<label for="naziv"></label>
<input type="text" name="naziv" id="sifra" value="<?=$pica->naziv?>" />
</label>
<h3>Cijena</h3>
<label for="Cijena"></label>
<input type="text" name="cijena" id="sifra" value="<?=$pica->cijena?>">
<h3>Vrsta</h3>
<label for="vrsta"></label>
<input type="text" name="vrsta" id="sifra" value="<?=$pica->vrsta?>">
<input type="hidden" name="sifra" value="<?=$pica->sifra?>">
<div style="display:flex; flex-direction:column;">
    <button type="submit"  class="btn btn-primary btn-block">Uredi</button>
    <button  onclick="location.href = '<?=App::config('url')?>pice/index';" type="button" class="btn btn-danger btn-block">Odustani</button>
</div>

</div>
</div>

<?=$poruka?>
</fieldset>

</form>
