
    
<div class="grid-x">
<div class ="cell-large-6" style="display:flex; align-items:center">
<p class="h1">Rezervacija</p>
    <i 
        style="color:#007bff; margin-left:10px" 
        class="fas fa-2x fa-bell">
    </i> </p>
    </div>

<a href="<?=App::config('url') ?>rezervacija/novi"><i 
 style="color: green;"
 title="Dodaj novi" 
 class="fas fa-2x fa-plus"></i></a>


<table class="table">
    <thead class="thead-dark">
        <tr>
            <th>Datum</th>
            <th>Osoba</th>
            <th> Broj rezerviranih mjesta</th>
            <th> Mjesto</th>
            <th> Kontakt</th>
            <th> Napomena</th>
            <th> Akcija</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($rezervacija as $z): ?>
            <tr>
                <td><?=$z->datumiVrijeme?></td>
                <td><?=$z->osoba?> </td>
                <td><?=$z->brojRezerviranihMjesta?></td>
                <td><?=$z->mjesto?></td>
                <td><?=$z->kontakt?></td>
                <td><?=$z->napomena?></td>
                <td>
<a href="<?=App::config('url') ?>rezervacija/promjena/<?=$z->sifra?>">
<i style="color: black;"
 title="promjeni" 
 class="fas fa-2x fa-pen"></i>
</a>

<a href="<?=App::config('url') ?>rezervacija/brisanje/<?=$z->sifra?>">
<i style="margin-left:20px;"
 title="izbrisi" 
 class="fas fa-2x fa-trash"></i>
</a>
</td>

            </tr>
        <?php endforeach; ?>
    </tbody>
</table>

    



