
    
<div class="grid-x">
    <div class ="cell-large-6">
        <h1 style="font-size:1.5rem;"> rezervacija <i 
        style="color:yellow" 
        class="fas fa-1x fa-bell">
    </i> </h1>
    </div>
</div class ="cell-large-6" style="tet-align:right;">
<a href="<?=App::config('url') ?>rezervacija/novi"><i 
 style="color: green;"
 title="Dodaj novi" 
 class="fas fa-2x fa-plus"></i></a>


<table>
    <thead>
        <tr>
            <th>Datum</th>
            <th>osoba</th>
            <th> brojRezerviranihMjesta</th>
            <th> mjesto</th>
            <th> kontakt</th>
            <th> napomena</th>
            <th> akcija</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($rezervacija as $z): ?>
            <tr>
                <td><?=$z->datumiVrijeme?></td>
                <td><?=$z->osoba?> </td>
                <td><?=$z->brojRezerviranihMjesta?></td>
                <td><?=$z->mjesto?></td>
                <td><?=$z->kontakt?></td>
                <td><?=$z->napomena?></td>
        </tr>
<a href="<?=App::config('url') ?>rezervacija/promjena/<?=$z->sifra?>">
<i style="color: black;"
 title="promjeni" 
 class="fas fa- fa-pen"></i>
</a>

<a href="<?=App::config('url') ?>rezervacija/brisanje/<?=$z->sifra?>">
<i style="margin-left:20px;"
 title="izbrisi" 
 class="fas fa- fa-trash"></i>
</a>
</td>

            </tr>
        <?php endforeach; ?>
    </tbody>
</table>

    



