<div class="grid-x">
    <div class ="cell-large-6"  style="display:flex; align-items:center">
    <p class="h1">Jela</p>
    <i

    style="color:#007bff; margin-left:10px" 
        class="fas fa-2x fa-utensils"></i>
 </p>
    
    </div>

<a href="<?=App::config('url') ?>jelo/novi"><i 
 style="color: #007bff; "
 title="Dodaj novi" 
 class="fas fa-2x fa-plus"></i></a>
</div>


 <table class="table">
  <thead class="thead-dark">
  <tr>
            <th>Naziv</th>
            <th>Cijena</th>
            <th>Vrsta</th>
            <th>Akcija</th>
       </tr>
  </thead>
  <tbody>
        <?php foreach($jelo as $jela): ?>
            <tr>
                <td><?=$jela->naziv?></td>
                <td><?=$jela->cijena?> </td>
                <td><?=$jela->vrsta?></td>
                <td>
<a href="<?=App::config('url') ?>jelo/promjena/<?=$jela->sifra?>">
<i style="color: black; "
 title="promjeni" 
 class="fas fa-2x fa-pen"></i>
</a>

<a href="<?=App::config('url') ?>jelo/brisanje/<?=$jela->sifra?>">
<i style="margin-left:20px;  "
 title="izbrisi" 
 class="fas fa-2x fa-trash"></i>
</a>
</td>

            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
