<form action="<?=App::config('url') ?>jelo/dodajNovi" method="post">
<fieldset>
    <div style="display:flex; justify-content:center ">
    <div style="width:600px; ">

<p class="h1">Dodaj jelo</p>

<label>
    <h3>Naziv</h3>
<label for="naziv"></label>
<input type="text" name="naziv" id="sifra" value="<?=$jelo->naziv?>" />
</label>
<h3>Cijena</h3>
<label for="Cijena"></label>
<input type="number" name="cijena" id="sifra" value="<?=$jelo->cijena?>">
<h3>Vrsta</h3>
<label for="vrsta"></label>
<input type="text" name="vrsta" id="sifra" value="<?=$jelo->vrsta?>">


    
    <div style="display:flex; flex-direction:column;">
    <button type="submit"  class="btn btn-primary btn-block">Dodaj</button>
    <button  onclick="location.href = '<?=App::config('url')?>jelo/index';" type="button" class="btn btn-danger btn-block">Odustani</button>
</div>

</div>
</div>
<?=$poruka?>
</fieldset>

</form>