<form action="<?=App::config('url') ?>jelo/dodajNovi" method="post">
<fieldset>
 <legend>
     Dodavanje novih Jela
 </legend>

<label>
    <h3>Naziv</h3>
<label for="naziv"></label>
<input type="text" name="naziv" id="sifra" value="<?=$jelo->naziv?>" />
</label>
<h3>Cijena</h3>
<label for="Cijena"></label>
<input type="number" name="cijena" id="sifra" value="<?=$jelo->cijena?>">
<h3>Vrsta</h3>
<label for="vrsta"></label>
<input type="text" name="vrsta" id="sifra" value="<?=$jelo->vrsta?>">

<div class="grid-x grid-padding-x">
    <div class="large-4 cell">
    <a class="alert button expanded"
    href="<?=App::config('url')?>jelo/index">Odustani </a>   
    </div>
    <div class="large-8cell"></div>
    <input type="submit" class="success button expanded" value="Dodaj ">
</div>


<?=$poruka?>
</fieldset>

</form>