<form action="<?=App::config('url') ?>jelo/promjeni" method="post">
<fieldset>
 <legend>
   promijeni jela
 </legend>

<label>
    <h3>Naziv</h3>
<label for="naziv"></label>
<input type="text" name="naziv" id="sifra" value="<?=$jela->naziv?>" />
</label>
<h3>Cijena</h3>
<label for="Cijena"></label>
<input type="number" name="cijena" id="sifra" value="<?=$jela->cijena?>">
<h3>Vrsta</h3>
<label for="vrsta"></label>
<input type="text" name="vrsta" id="sifra" value="<?=$jela->vrsta?>">
<input type="hidden" name="sifra" value="<?=$pica->sifra?>">
<div class="grid-x grid-padding-x">
    <div class="large-4 cell">
    <a class="alert button expanded"
    href="<?=App::config('url')?>jelo/index">Odustani </a>   
    </div>
    <div class="large-8cell"></div>
    <input type="submit" class="success button expanded" value="promjeni ">
</div>


<?=$poruka?>
</fieldset>

</form>